### ISSUE TITLE
Packaging the app

### ISSUE THREAD

**Issue by adriatic** [paulvanbladel/aurelia-admin-sample#2]
This is a good opportunity to define our standard packaging. For example I do not like the sequences like

```
cd server
npm install
cd ../../cliend
do whatever needs to be done here ...
```

Not having the run unstructions, I assumed that I can run the app from the root folder by typing

```
node server/app
```

but that does not seem to be the case as I got 

```
=> node server/app
loading configuration for environment : development
module.js:338
    throw err;
    ^
Error: Cannot find module './config.development'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/congral/work/AureliaApps/aurelia-admin-sample/server/config/index.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/congral/work/AureliaApps/aurelia-admin-sample/server/app.js:13:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
=> 
```

**Comment by paulvanbladel** [comment]
after npm in both client and server and jspm  in client it can be simply started as any other aurelia app:
from the client folder: gulp watch.
There is an additional gulp task for spinning up the node server.
Obviously, the info about copying the config.production.js into config.development was missing in the readme.

cheers
paul.

**Comment by adriatic** [comment]
I completely changed my mind once I learned more about the interactions between npm and jspm. Configuration for the client has to be completely separate from the server configuration - and as you stated, gulp can handle both being aware of the separation issues. 

All this still does not mean that our [ASM - Application Structure Manager](https://gitter.im/adriatic/ASM) is in any way prevented to create the whole setup - gulp included
